name: 'GitHub Trello Poster'
description: 'Link a pull request to a Trello card'
inputs:
  comment-body:
    required: true
  github-url:
    required: true
  attachment-name:
    description: 'The display text to use in Trello. If not supplied, Trello will default to using the URL.'
    required: false
  trello-api-token:
    required: true
  trello-api-key:
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
