name: Test
on:
  pull_request:
    types: [created, edited, synchronize]
jobs:
  trello-poster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lfdebrux/trello-poster-action@HEAD
        uses: ./
        with:
          comment-body: ${{ github.event.pull_request.body }}
          github-url: ${{ github.event.pull_request.html_url }}
          trello-api-token: ${{ secrets.TRELLO_API_TOKEN }}
          trello-api-key: ${{ secrets.TRELLO_API_KEY }}
